sudo: required
language: python
services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
# services:
#   - docker
install:
  - pip install -r requirements-test.txt
  - pip install -r requirements.txt
  - pip install -e .
  - python hfos_manage.py install provisions
#  - docker build -t hackerfleet/hfos -f docker/Dockerfile.debian .
script: python setup.py test
# -  docker run -i -t hackerfleet/hfos /etc/init.d/mongodb start && py.test tests
after_success:
  - coveralls
notifications:
  irc:
    channels:
      - "chat.freenode.org#hackerfleet"
    on_success: change
    use_notice: true
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} ( %{duration}, %{build_url} )"
  email:
    recipients:
        - riot@c-base.org
    on_success: change

