#!/bin/bash

# Check if root
if [ "$EUID" -ne 0 ]
then
    echo "You need root privileges to install HFOS. Use su or sudo."
    exit
fi

# Find our package manager
if VERB="$( which apt-get )" 2> /dev/null; then
    echo "Debian-based"

    if [ ! -f /etc/apt/sources.list.d/nodesource.list ]
    then
        echo "Adding node source Debian repository."
        apt-get install apt-transport-https
        echo "deb https://deb.nodesource.com/node_7.x jessie main
deb-src https://deb.nodesource.com/node_7.x jessie main" > /etc/apt/sources.list.d/nodesource.list
        wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
        apt-get update
    fi

    apt-get install mongodb python3.5 python3-pip python3-grib \
                    python3-bson python3-pymongo python3-serial \
                    python3-pymongo-ext python3-bson-ext \
                    npm nodejs enchant nginx virtualenv\
                    gdal-bin python-gdal

    npm install -g npm@4.2.0

    git submodule init
    git submodule update

    virtualenv -p /usr/bin/python3.5 --system-site-packages venv
    source venv/bin/activate
    pip install -Ur requirements-dev.txt
    python setup.py develop

    systemctl start mongodb.service

    venv/bin/python hfos_manage.py install all

    echo "Done!"
elif VERB="$( which yum )" 2> /dev/null; then
    echo "Modern Red Hat-based - NOT SUPPORTED YET"
elif VERB="$( which portage )" 2> /dev/null; then
    echo "Gentoo-based - NOT SUPPORTED YET"
elif VERB="$( which pacman )" 2> /dev/null; then
    echo "Arch-based - NOT SUPPORTED YET"
else
    echo "Your distribution is not yet supported." >&2
    exit 1
fi


